/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "home": [],
    "dashboard": [],
    "admin": [],
    "admin.dev": [],
    "admin.config": [],
    "admin.config.update": [],
    "admin.config.updateOrder": [],
    "admin.chapters": [],
    "admin.tools": [],
    "admin.challenges": [],
    "admin.widgets": [],
    "admin.widgets.refresh": [],
    "widgets.update": [
        {
            "name": "widget",
            "required": true,
            "binding": "id"
        }
    ],
    "widgets.components": [],
    "admin.users": [],
    "admin.users.create": [],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "toggleChapterActive": [
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        }
    ],
    "users.team.toggle": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        },
        {
            "name": "team",
            "required": true,
            "binding": "id"
        }
    ],
    "teams.store": [],
    "teams.destroy": [
        {
            "name": "team",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.illustrations.index": [],
    "api.update.a.value": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "translations.index": [
        {
            "name": "language",
            "required": true,
            "binding": "slug"
        }
    ],
    "translations.show": [
        {
            "name": "language",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "game",
            "required": true
        }
    ],
    "translation.books": [
        {
            "name": "language",
            "required": true,
            "binding": "slug"
        }
    ],
    "translations.units": [
        {
            "name": "book",
            "required": true,
            "binding": "id"
        }
    ],
    "translations.words": [
        {
            "name": "unit",
            "required": true,
            "binding": "id"
        }
    ],
    "translations.import": [],
    "translation.books.create": [],
    "translations.create": [],
    "translations.words.update": [
        {
            "name": "translation",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.validate": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.show": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.edit": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.duplicate": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.update": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.storeTo": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "questions.updateOrder": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "questions.answers.reset": [
        {
            "name": "type",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "questions.batch.updateDisplayIf": [],
    "questions.updateDisplayIf": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.moveTo.post": [
        {
            "name": "question",
            "required": true,
            "binding": "id"
        },
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "questions.destroy": [
        {
            "name": "question",
            "required": true
        }
    ],
    "blocks.show": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.edit": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.blocks.store": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.update": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.updateTemplate": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.blur": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.switch": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.moveTo.post": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        },
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.moveTo.chapter": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        },
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.move": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.destroy": [
        {
            "name": "block",
            "required": true
        }
    ],
    "illustrations.show": [
        {
            "name": "illustration",
            "required": true,
            "binding": "id"
        }
    ],
    "illustrations.edit": [
        {
            "name": "illustration",
            "required": true,
            "binding": "id"
        }
    ],
    "illustrations.store": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "images.upload": [],
    "illustrations.update": [
        {
            "name": "illustration",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.illustrations.order": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "blocks.updateIllustrationsGrid": [
        {
            "name": "block",
            "required": true,
            "binding": "id"
        }
    ],
    "illustrations.destroy": [
        {
            "name": "illustration",
            "required": true
        }
    ],
    "chapters.formulas.index": [
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        }
    ],
    "chapters.theorems.index": [
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        }
    ],
    "formulas.index": [],
    "formulas.multiple": [
        {
            "name": "formula",
            "required": true
        }
    ],
    "formulas.store": [
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        }
    ],
    "formulas.duplicate": [
        {
            "name": "formula",
            "required": true,
            "binding": "id"
        }
    ],
    "formulas.updateOrder": [],
    "formulas.destroy": [
        {
            "name": "formula",
            "required": true
        }
    ],
    "posts.show": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.edit": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.info": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "chapters.posts.store": [
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        }
    ],
    "posts.update": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.updateBlocksOrder": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.updateQuestionsGrid": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.destroy": [
        {
            "name": "post",
            "required": true
        }
    ],
    "scores.post": [
        {
            "name": "post",
            "required": true,
            "binding": "id"
        }
    ],
    "scores.challenge": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        }
    ],
    "generators.index": [],
    "generators.edit": [
        {
            "name": "generator",
            "required": true,
            "binding": "id"
        }
    ],
    "generators.store": [],
    "generators.update": [
        {
            "name": "generator",
            "required": true,
            "binding": "id"
        }
    ],
    "generators.destroy": [
        {
            "name": "generator",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.show": [
        {
            "name": "challenge",
            "required": true,
            "binding": "slug"
        }
    ],
    "chapters.challenge": [
        {
            "name": "theme",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "challenge",
            "required": true,
            "binding": "slug"
        }
    ],
    "chapters.challenges.store": [
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.update": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.destroy": [
        {
            "name": "challenge",
            "required": true
        }
    ],
    "challenges.generators.index": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.generators.updateOrder": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.generators.store": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.generators.attach": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        },
        {
            "name": "generator",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.generators.detach": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        },
        {
            "name": "generator",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.edit": [
        {
            "name": "challenge",
            "required": true,
            "binding": "id"
        }
    ],
    "challenges.team": [
        {
            "name": "theme",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "challenge",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "team",
            "required": true,
            "binding": "name"
        }
    ],
    "teams.index": [],
    "teams.show": [
        {
            "name": "team",
            "required": true,
            "binding": "name"
        }
    ],
    "teams.challenge": [
        {
            "name": "team",
            "required": true,
            "binding": "name"
        },
        {
            "name": "challenge",
            "required": true,
            "binding": "slug"
        }
    ],
    "teams.chapters.stats": [
        {
            "name": "team",
            "required": true,
            "binding": "name"
        },
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        }
    ],
    "decks.index": [],
    "decks.show": [
        {
            "name": "deck",
            "required": true,
            "binding": "slug"
        }
    ],
    "decks.edit": [
        {
            "name": "deck",
            "required": true,
            "binding": "slug"
        }
    ],
    "decks.addFlipcard": [
        {
            "name": "deck",
            "required": true,
            "binding": "id"
        }
    ],
    "flipcards.destroy": [
        {
            "name": "flipcard",
            "required": true,
            "binding": "id"
        }
    ],
    "decks.store": [],
    "decks.update": [
        {
            "name": "deck",
            "required": true,
            "binding": "id"
        }
    ],
    "decks.destroy": [
        {
            "name": "deck",
            "required": true,
            "binding": "id"
        }
    ],
    "decks.updateOrder": [],
    "decks.assignChapter": [
        {
            "name": "deck",
            "required": true,
            "binding": "id"
        }
    ],
    "dev": [
        {
            "name": "dev",
            "required": true
        }
    ],
    "dev.index": [],
    "tools": [],
    "tools.tool": [
        {
            "name": "tool",
            "required": true,
            "binding": "slug"
        }
    ],
    "tools.edit": [
        {
            "name": "tool",
            "required": true,
            "binding": "id"
        }
    ],
    "tools.update": [
        {
            "name": "tool",
            "required": true,
            "binding": "id"
        }
    ],
    "quizzs.index": [],
    "quizzs.sessions.show": [
        {
            "name": "quizzSession",
            "required": true,
            "binding": "shortcode"
        }
    ],
    "quizzs.admin": [],
    "quizzs.admin.quizz": [
        {
            "name": "quizz",
            "required": true,
            "binding": "id"
        }
    ],
    "quizzs.sessions.dashboard": [
        {
            "name": "quizzSession",
            "required": true,
            "binding": "shortcode"
        }
    ],
    "quizzs.sessions.projection": [
        {
            "name": "quizzSession",
            "required": true,
            "binding": "shortcode"
        }
    ],
    "quizzs.store": [],
    "quizzs.destroy": [
        {
            "name": "quizz",
            "required": true,
            "binding": "id"
        }
    ],
    "quizzs.sessions.create": [
        {
            "name": "quizz",
            "required": true,
            "binding": "id"
        }
    ],
    "quizzs.sessions.destroy": [
        {
            "name": "quizzSession",
            "required": true,
            "binding": "id"
        }
    ],
    "quizzs.sessions.updateCurrent": [
        {
            "name": "quizzSession",
            "required": true,
            "binding": "shortcode"
        }
    ],
    "quizzs.sessions.updateEnable": [
        {
            "name": "quizzSession",
            "required": true,
            "binding": "shortcode"
        }
    ],
    "quizzs.update": [
        {
            "name": "quizz",
            "required": true,
            "binding": "id"
        }
    ],
    "evaluations.show": [
        {
            "name": "evaluation",
            "required": true,
            "binding": "slug"
        }
    ],
    "latex.pdf": [],
    "latex.links": [],
    "latex.download": [
        {
            "name": "fileID",
            "required": true
        }
    ],
    "bareme.show": [],
    "grapheur.show": [],
    "grapheur.download": [],
    "theme": [
        {
            "name": "theme",
            "required": true,
            "binding": "slug"
        }
    ],
    "themes.chapters.intro": [
        {
            "name": "theme",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        }
    ],
    "chapters.slide": [
        {
            "name": "chapter",
            "required": true
        },
        {
            "name": "order",
            "required": true
        }
    ],
    "chapters.show": [
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        }
    ],
    "themes.chapters.slide": [
        {
            "name": "theme",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "order",
            "required": true
        }
    ],
    "themes.chapters.slide.anchor": [
        {
            "name": "theme",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "chapter",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "order",
            "required": true
        },
        {
            "name": "type",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "chapters.edit": [
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        }
    ],
    "themes.chapters.store": [
        {
            "name": "theme",
            "required": true,
            "binding": "slug"
        }
    ],
    "chapters.update": [
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        }
    ],
    "chapters.destroy": [
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        }
    ],
    "chapters.currentPost": [
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        }
    ],
    "chapters.updatePostsOrder": [
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        }
    ],
    "chapters.index.min": [],
    "chapters.relations.toggle": [
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        },
        {
            "name": "related",
            "required": true,
            "binding": "id"
        }
    ],
    "chapters.info": [
        {
            "name": "chapter",
            "required": true,
            "binding": "id"
        }
    ]
}
}
export {};
