
export const greekLaTeX: Record<string, string> = {
	a: '\\alpha', A: '\\Alpha',
	b: '\\beta', B: '\\Beta',
	d: '\\delta', D: '\\Delta',
	e: '\\epsilon', E: '\\Epsilon',
	g: '\\gamma', G: '\\Gamma',
	h: '\\eta', H: '\\Eta',
	i: '\\iota', I: '\\Iota',
	k: '\\kappa', K: '\\Kappa',
	l: '\\lambda', L: '\\Lambda',
	m: '\\mu', M: '\\Mu',
	n: '\\nu', N: '\\Nu',
	o: '\\omicron', O: '\\Omicron',
	p: '\\pi', P: '\\Pi',
	r: '\\rho', R: '\\Rho',
	s: '\\sigma', S: '\\Sigma',
	t: '\\tau', T: '\\Tau',
	u: '\\upsilon', U: '\\Upsilon',
	w: '\\omega', W: '\\Omega',
	x: '\\chi', X: '\\Chi',
	y: '\\psi', Y: '\\Psi',
	z: '\\zeta', Z: '\\Zeta',
	q: '\\theta', Q: '\\Theta',
	c: '\\xi', C: '\\Xi',
	f: '\\phi', F: '\\Phi',
	j: '\\varphi', J: '\\Phi',
}
